<?php

?>
<!DOCTYPE html>
<html>

<head>
    <title> </title>


</head>

<body>
    <script>
        class LifeInsurance {
            constructor(KeyTerms, KeyWords) {
                this.KeyTerms = KeyTerms,
                this.KeyWords = KeyWords 
            }
            test() {

            }
        }

        let Chapter1KeyTerms = [
            "Stock Companies",
            "Mutual Companies",
            "Lloyd's of London",
            "Reinsurers",
            "1945 McCarren - Ferguson Act",
            "1970 Fair Credit Reporting Act",
            "National Association of Insurance Commissioners",
            "State Guarantee Association",
            "AM Best",
            "Standard and Poor's",
            "Moody's",
            "Fitch"
        ];

        let Chapter1KeyWords = [
            {word: "Actuarial Department", definition: "This is the department that calculates policy rates, reserves, and dividends."},
            {word: "Adjuster", definition: "This is person who investigates claims and arranges for them to be settled or denied"},
            {word: "Alien Insurer", definition: "In the Untied States, this is an insurer whose principal office and domicile location is outside this country"},
            {word: "Agent", definition: "This is an individual or organization that's authorized to solicit, sell and transact (bind) coverage for specific insurance providers under the terms of one or more agent contracts."},
            {word: "Authorized Insurer", definition: "This is an admitted insurer"},
            {word: "Captive Insurer", definition: "This is a person who represents himself and the insured (i.e., the client or customer). A broker cannot bind coverage on behalf of an insurance carrier because a broker is not appointed as an agent"},
            
            {word: "Certificate of Authority", definition: "This is a license that's issued to an insurer by an insurance department (or equivalent state agency) that authorizes that company to conduct insurance business in that particular state"},
            {word: "Claims Department", definition: "This is the department that's responsible for processing, investigating, and paying claims"},
            {word: "Divisible Surplus", definition: "This is the amount of earnings that are paid to policy owners as dividends after the insurance company sets aside funds required to cover reserves, operating expenses, and general business purposes."},
            {word: "Domestic Insurer", definition: "This is an insurer with its principal or home office in the state in which it's authorized"},
            {word: "Foreign Insurer", definition: "This is an insurer whose principal office or domicile location is in a state that's different from the state in which it's transacting insurance business."},
            {word: "Fraternal Benefit Society", definition: "This is a non-profit benevolent organization that provides insurance to its members."},
            {word: "Independent Insurance Agency", definition: "This is an agency that can represent any number of insurance companies through contractual agreements. Unlike a captive agency, they are not limited to one insurance company"},
            {word: "Insurance", definition: "This is the transfer of risk through the pooling or accumulation of funds."},
            {word: "Insured", definition: "This is the customer who receives insurance protection under an insurance policy."},
            {word: "Insurer", definition: "This is an insurance company"},
            {word: "Lloyds of London", definition: "This is NOT an insurer but a group of individuals and companies that underwrite unusual insurance policies."},
            {word: "Marketing Division", definition: "This is the division that's responsible for acquiring prospective applicants through various advertising media."},
            {word: "Monoline Insurer", definition: "This is an insurance carrier that only sells one line of insurance."},
            {word: "Multi-Line Insurer", definition: "This is an insurance company or independent agent that provides a 'one-stop-shop' for businesses or individuals who are seeking coverage for all of their insurance needs. For example, many large insurers offer individual policies for automobile, homeowner, long-terms care, life and health insurance needs."},
            {word: "Mutual Insurance Company", definition: "This is an insurance comapny that's characterized by having no capital stock, being owned by their policy owners, and typically issuing participating insurance."},
            {word: "Non-Admitted (Unauthorized) Insurer", definition: "This is an insurer that has not received a certificiate of authority from a state's department of insurance which authorizes it to conduct insurance business in that state."},
            {word: "Nonparticipating Policy", definition: "This is a policy that's typically issued by stock companies. This tpe of policy doesn't allow policy owners to participate in dividends or to elect the boards of directors. "},
            {word: "Participating Policy", definition: "This is an insurance policy that pays policy dividends to policy owners. By receiving dividends, policy owners share in the copmany's divisible surplus and also elect the company's board of directors."},
            {word: "Personal Producing General Agency (PPGA)", definition: "THis is an agency that represents one or more specific insurers. A PPGA is a similar agency system, but PPGAs don't recruit, train, or supervise career agents."},
            {word: "Policy Owner", definition: "This is the person who's responsible for the payment of premiums and who possesses all ownership rights of the contract. Typically, the policy owner is also the insured."},
            {word: "Private (Commercial) Insurer", definition: "This is an insurer that's owned by private citizens or groups that offer one or more insurance lines. Commercial insurers are NOT government-owned"},
            {word: "Producer", definition: "This is an individual who's licensed by one or more states to sell, solicit, or transact insurance in a given state."},
            {word: "Proposed Insured", definition: "This is the person whose life will be covered by an insurance policy. (See also: Insured"},
            {word: "Public Adjuster", definition: "This person acts on behalf of a consumer who's settling an insurance claim."},
            {word: "Reciprocal Insurer", definition: "This is an unincorporated organization in which all members insure one another. An attorney-in-fact manages it."},
            {word: "Reinsurance", definition: "This is the acceptance by one or more insurers (referred to as reinsureres) of a portions of the risk being underwritten  by another insurer that has contracted with a consumer to cover the entire risk."},
            {word: "Reinsurer", definition: "This is a company that provides financial protection to insurance companies. Reinsurers handle risks that are too large for insurance companies to cover on their own and make it possible for insurers to botain more business than they would otherwise be able to obtain."},
            {word: "Risk Retention Group", definition: "This is a group-owned liability insurer that assumes and spreads product liability and other forms of commerical liability risks among its members."},
            {word: "Sales Department", definition: "This department acquires clients through one-on-one meetings in which consumers complete applications"},
            {word: "Self-Insurer", definition: "This is a company that establishes a self-funded plan to cover potential loesses rather than transferring the risk to an insurance company."},
            {word: "Service Representatives", definition: "These are customer service employees. Service representatives are not required to obtain a license because they neither sell nor solicit coverage, and they don't bind coverage."},
            {word: "Solicitors", definition: "These are the individuals who solicit and schedule sales meetings between consumers and the producers for whom they work. Some states separetaly license these individuals."},
            {word: "Stock Insurance Company", definition: "This is an insurance company that's owned and controlled by a group of stockholders (or shareholders) whose investment in the company provides the safety margin necessary in the issuance of guaranteed, fixed premium, nonparticipating policies."},
            {word: "Surplus Lines Insurance", definition: "This is non-traditional insurance that's only available from a surplus lines insurer. This type of insurance provides coverage for substandard or unusual risks and is not available through private or commerical carriers. "},
            {word: "Unauthorized Insurer", definition: "This is a non-admitted insurer."},
            {word: "Underwriting Department", definition: "This is the department within an insurance company that's responsible for reviewing applications, approving or declining applications, and assigning risk classifications."}
        ];

        let Chapter1Sections = [
            {
                section: "The Concept of Insurance",
                defintion: "The transfer of risk from one party to another through a legal contract.",
                content: {
                    part1: "A Solution to Economic Uncertainities and Losses",
                    info1: "Insurance contracts indemnify policyholders, which means the policies restore insureds to the financial position they experienced before the insured loss.",
                    info2: "The 'principle of indemnity' states that the goal of an action is to 'restore' an insured to the same financial position they were in prior to when the loss in question occurred. Insurance contracts indemnify insureds.",
                    info3: "Life insurance policies are 'valued contracts' because they pay a predetermined amount regardless of the actual loss that was incurred.",
                }
            },
            {
                section: "Types of Insurance Companies",
                defintion: "Private Insurance, Government (Social Insurance), Self-Insurers",
                content: {
                    info1: "Private Insurance: Private citizens or groups own commerical insurance companies, which may be proprietary or cooperative. These private insurers offer individual, group, industrial, or blanket insurance policies.",
                    info2: "Government (Social Insurance): Government (Federal and state governments) also offer a variety of coverage. Federal and state government provided insurnace programs are commonly referred to as social insurance. Social insurance programs range from crop insurance to FDIC insurance on bank deposits.",
                    info3: "Self-Insurers: Although self-insurance is not a method of transferring risk, it's an important concept to understand. Rather than transfer risk to an insurance company, a self-insurer establishes a self-funded plan to cover potential losses.",
                    info4: ""
                }
            },
            {
                section: "Insurer Classifications",
                content: {

                }
            },
            {
                section: "Departments Within an Insurance Company",
                content: {

                }
            },
            {
                section: "Key People Within an Insurance Company",
                content: {

                }
            },
            {
                section: "How Insurance is Sold",
                content: {

                }
            },
            {
                section: "Evolution of Industry Oversight",
                content: {

                }
            }
        ];

        let ChapterSections = [
            {
                section: "",
                content: {
                    
                }
            }

        ];
        let Chapter1 = LifeInsurance(Chapter1KeyTerms);

        let Chapter1KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter2 = new LifeInsurance();

        let Chapter2KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter3 = new LifeInsurance();

        let Chapter3KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter4 = new LifeInsurance();

        let Chapter4KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter5 = new LifeInsurance();

let Chapter5KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter6 = new LifeInsurance();
        let Chapter6KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ]
        let Chapter7 = new LifeInsurance();

        let Chapter7KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter9 = new LifeInsurance();

        let Chapter9KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter10 = new LifeInsurance();

        let Chapter10KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter11 = new LifeInsurance();

        let Chapter11KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter12 = new LifeInsurance();

        let Chapter12KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ]

        let Chapter13 = new LifeInsurance();

        let Chapter13KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter14 = new LifeInsurance();

        let Chapter14KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter15 = new LifeInsurance();

        let Chapter15KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter16 = new LifeInsurance();

        let Chapter16KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter17 = new LifeInsurance();

        let Chapter17KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter18 = new LifeInsurance();

        let Chapter18KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter19 = new LifeInsurance();

        let Chapter19KeyWords = [
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""},
            {word: "", definition: ""}
        ];

        let Chapter20 = new LifeInsurance();
    </script>
</body>

</html>